### ISSUE TITLE
Make sure reports can be saved.

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#344]
Currently, after a report is created, it can't be saved in the Equalify frontend.

**Comment by bbertucc** [comment]
I checked and this is working.

**Comment by kevinandrews1** [comment]
Reopen and assign to me so I can test this functionality @bbertucc?

**Comment by bbertucc** [comment]
Good idea @kevinandrews1. Reopened and assigned.

**Comment by kevinandrews1** [comment]
I created a report but don't see a save button or anything. am I missing something? Can you clarify how to save a report @bbertucc?

**Comment by bbertucc** [comment]
@kevinandrews1 - the save button should be when you're editing a report

**Comment by kevinandrews1** [comment]
@bbertucc The label is "Create report". I assume this is where you're talking about--but it's not save--so just confirming before i close.

**Comment by bbertucc** [comment]
@kevinandrews1 it's reverted! after you create a report, you should have an option to "Update report". This isn't just an accessibility issue. The option is not there at all. Adding @wilsuriel03 back on this ticket.

@wilsuriel03 the "Update" button worked when we were changing filters, but it doesn't seem to work anymore.

**Comment by wilsuriel03** [comment]
@bbertucc I have not worked on this feature, can you give more context. Im a bit confused on what you are referring to. @heythisischris  worked on this.

**Comment by bbertucc** [comment]
K. Adding back @heythisischris. Not sure why the save functionality doesn't work anymore?

**Comment by heythisischris** [comment]
Fixed!

**Comment by bbertucc** [comment]
@heythisischris I tested this again today, and it's still not working. Hmph.

**Comment by heythisischris** [comment]
@bbertucc Fixed, the production branch did not deploy when I pushed yesterday, it's working now! Should stay working.
