### ISSUE TITLE
Results not being filtered when message filters are added 

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#412]
I added the "some pages must contain landmarks" filter message to my report. I expected to only see results that had that filter. Instead I saw everything.

using my user `apikey`: `c0815b05ae95494894037b3106d42109`

running the query `{{api_url}}/get/results?reportId=52330930-922d-484c-b24f-be6e501e309a`

results in:
```
{
    "reportName": "Equalify Website",
    "urls": [
        {
            "id": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "url": "https://equalify.app/"
        },
        {
            "id": "3020c3f0-c850-443d-beb2-8768175dfc1f",
            "url": "https://equalify.app/equalify-snippets-video-unique-aria-labels/"
        },
        {
            "id": "4cb5098d-34a9-46fb-b4d5-6ce071418ca0",
            "url": "https://equalify.app/version-one-preview/"
        },
        {
            "id": "bd0438e1-530a-4cf9-8e6d-d464b590e161",
            "url": "https://equalify.app/helping-wordpress-org-become-accessible/"
        },
        {
            "id": "1bf5496c-2f48-4d1d-91ee-42b99eae9f00",
            "url": "https://equalify.app/a11ys-ai-future-the-future-is-now/"
        },
        {
            "id": "c2ebd5fb-7158-4b01-8541-0389b5877508",
            "url": "https://equalify.app/fixed/"
        }
    ],
    "nodes": [
        {
            "nodeId": "039e2c23-9e8d-4222-9c4d-2d325e01b015",
            "html": "<div class=\"html5-video-player ytp-exp-bottom-control-flexbox ytp-modern-caption ytp-title-enable-channel-logo ytp-fine-scrubbing-exp ytp-embed ytp-embed-playlist unstarted-mode ytp-hide-controls ytp-small-mode\" tabindex=\"-1\" id=\"movie_player\" data-version=\"/s/player/250a2ff7/player_ias.vflset/en_US/base.js\" aria-label=\"YouTube Video Player\">",
            "targets": [
                "iframe",
                "#movie_player"
            ],
            "relatedUrlId": "c2ebd5fb-7158-4b01-8541-0389b5877508",
            "equalified": false
        },
        {
            "nodeId": "0f8f132d-fc9b-4c95-9773-156a29cd3619",
            "html": "<select name=\"input_3\" id=\"input_2_3\" class=\"large gfield_select\" aria-required=\"true\" aria-invalid=\"false\"><option value=\"No thanks!\">No thanks!</option><option value=\"Yes, please email me about a demo.\">Yes, please email me about a demo.</option></select>",
            "targets": [
                "#input_2_3"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "10dc0194-4542-4085-8711-ccada479c885",
            "html": "<div class=\"wp-block-group alignfull has-global-padding is-layout-constrained wp-container-core-group-is-layout-19 wp-block-group-is-layout-constrained\" style=\"border-top-color:var(--wp--preset--color--accent-5);border-top-width:1px;margin-top:0;padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--10);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--10)\">",
            "targets": [
                ".wp-container-core-group-is-layout-19"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "1b0fbcfe-1f19-41ed-bae7-9f3fb1861aa6",
            "html": "<h2 class=\"wp-block-heading\">Get the Latest!</h2>",
            "targets": [
                ".are-vertically-aligned-center > .wp-block-column.is-vertically-aligned-center.wp-block-column-is-layout-flow:nth-child(1) > .has-global-padding.is-layout-constrained.wp-block-group-is-layout-constrained > h2"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "1ba1da0f-51d4-4c49-8508-130c685fbba4",
            "html": "<a href=\"https://equalify.app/category/use-case/\" rel=\"tag\">Use Case</a>",
            "targets": [
                ".taxonomy-category > a[rel=\"tag\"]"
            ],
            "relatedUrlId": "bd0438e1-530a-4cf9-8e6d-d464b590e161",
            "equalified": false
        },
        {
            "nodeId": "1f7cb891-f6e5-4bc1-aec9-71872f9ac53c",
            "html": "<textarea id=\"comment\" name=\"comment\" cols=\"45\" rows=\"8\" maxlength=\"65525\" required=\"\"></textarea>",
            "targets": [
                "#comment"
            ],
            "relatedUrlId": "1bf5496c-2f48-4d1d-91ee-42b99eae9f00",
            "equalified": false
        },
        {
            "nodeId": "20d86429-a67f-4378-810b-7f1b93ff006e",
            "html": "<div class=\"gform-body gform_body\">",
            "targets": [
                ".gform-body"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "218310ca-bfa3-447c-957c-d825b061f93d",
            "html": "<p class=\"has-text-align-center has-small-font-size\"><em>Together we can Equalify the internet.</em></p>",
            "targets": [
                ".wp-container-core-group-is-layout-29 > .has-small-font-size.has-text-align-center"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "294b2476-92e3-4d47-9c76-3773183e0b16",
            "html": "<h2 class=\"wp-block-heading has-text-align-center is-style-default has-base-color has-text-color has-link-color wp-elements-2c5a5cd64a293274d72406b7a81ba5a7\" style=\"margin-top:0;margin-bottom:0\">Recent Updates</h2>",
            "targets": [
                ".wp-elements-2c5a5cd64a293274d72406b7a81ba5a7"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "29cef512-4882-4bee-8dd5-39a01d38f088",
            "html": "<video tabindex=\"-1\" class=\"video-stream html5-main-video\" webkit-playsinline=\"\" playsinline=\"\" controlslist=\"nodownload\" style=\"width: 500px; height: 281px; left: 0px; top: -281px;\"></video>",
            "targets": [
                "iframe[width=\"500\"]",
                "video"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "2b05b226-9f17-478f-b056-a04c41a4ddba",
            "html": "<h3 class=\"wp-block-heading has-text-align-center is-style-default\" style=\"margin-top:0\">Social Links</h3>",
            "targets": [
                ".wp-container-core-group-is-layout-29 > .is-style-default"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "2dea2686-87a1-45c5-ab8b-3b79c7618ea0",
            "html": "<select name=\"input_3\" id=\"input_2_3\" class=\"large gfield_select\" aria-required=\"true\" aria-invalid=\"false\"><option value=\"No thanks!\">No thanks!</option><option value=\"Yes, please email me about a demo.\">Yes, please email me about a demo.</option></select>",
            "targets": [
                "#input_2_3"
            ],
            "relatedUrlId": "3020c3f0-c850-443d-beb2-8768175dfc1f",
            "equalified": false
        },
        {
            "nodeId": "2e25fba8-16ab-49ab-8f3a-d1906803da09",
            "html": "<span class=\"wp-block-post-navigation-link__arrow-next is-arrow-arrow\" aria-hidden=\"true\">→</span>",
            "targets": [
                ".wp-block-post-navigation-link__arrow-next"
            ],
            "relatedUrlId": "3020c3f0-c850-443d-beb2-8768175dfc1f",
            "equalified": false
        },
        {
            "nodeId": "2e62fadf-79cb-458b-a6cb-2ebb21775a5f",
            "html": "<div class=\"wp-block-group alignfull has-base-2-background-color has-background is-layout-flow wp-block-group-is-layout-flow\" style=\"border-top-style:none;border-top-width:0px;border-right-style:none;border-right-width:0px;border-bottom-color:var(--wp--preset--color--contrast-3);border-bottom-width:1px;border-left-style:none;border-left-width:0px;margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--10);padding-right:var(--wp--preset--spacing--10);padding-bottom:var(--wp--preset--spacing--10);padding-left:var(--wp--preset--spacing--10)\">",
            "targets": [
                ".wp-block-group-is-layout-flow.has-base-2-background-color.alignfull"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "3107d433-197d-49c7-a159-9f0ea6f75c72",
            "html": "<span class=\"wp-block-post-navigation-link__arrow-next is-arrow-arrow\" aria-hidden=\"true\">→</span>",
            "targets": [
                ".wp-block-post-navigation-link__arrow-next"
            ],
            "relatedUrlId": "bd0438e1-530a-4cf9-8e6d-d464b590e161",
            "equalified": false
        },
        {
            "nodeId": "313e088e-b790-41e3-b3a0-75e630ea49da",
            "html": "<a class=\"wp-block-button__link has-contrast-2-color has-text-color has-link-color has-text-align-left wp-element-button\" href=\"https://calendly.com/equalifyapp/15-minute-demo\" style=\"border-width:2px;padding-top:var(--wp--preset--spacing--10);padding-right:var(--wp--preset--spacing--20);padding-bottom:var(--wp--preset--spacing--10);padding-left:var(--wp--preset--spacing--20)\">",
            "targets": [
                ".wp-container-core-buttons-is-layout-2 > .is-style-outline.is-style-outline--064448592694e5040dbfe16027fad2b4.wp-block-button > .has-contrast-2-color.wp-block-button__link.wp-element-button"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "33327295-5aab-4db4-b28c-0897e216742c",
            "html": "<span class=\"wp-block-social-link-label screen-reader-text\">Equalify LinkedIn</span>",
            "targets": [
                ".wp-social-link-linkedin > .wp-block-social-link-anchor > .wp-block-social-link-label.screen-reader-text"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "39bd0bdf-b3d7-4821-b072-76bb6f2f09f1",
            "html": "<select name=\"input_3\" id=\"input_2_3\" class=\"large gfield_select\" aria-required=\"true\" aria-invalid=\"false\"><option value=\"No thanks!\">No thanks!</option><option value=\"Yes, please email me about a demo.\">Yes, please email me about a demo.</option></select>",
            "targets": [
                "#input_2_3"
            ],
            "relatedUrlId": "1bf5496c-2f48-4d1d-91ee-42b99eae9f00",
            "equalified": false
        },
        {
            "nodeId": "3ab7d66d-4e1b-4f7b-9496-06b662da566c",
            "html": "<span class=\"wp-block-social-link-label screen-reader-text\">Equalify GitHub Organization</span>",
            "targets": [
                ".wp-social-link-github > .wp-block-social-link-anchor > .wp-block-social-link-label.screen-reader-text"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "4230e82e-59be-4991-b091-7ceb002a8f72",
            "html": "<div class=\"wp-block-group has-global-padding is-layout-constrained wp-block-group-is-layout-constrained\">",
            "targets": [
                ".wp-container-core-group-is-layout-7 > .has-global-padding.is-layout-constrained.wp-block-group-is-layout-constrained"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "43f391f2-9a9b-47ab-bb8c-2dd43310fee9",
            "html": "<span class=\"wp-block-post-navigation-link__arrow-previous is-arrow-arrow\" aria-hidden=\"true\">←</span>",
            "targets": [
                ".wp-block-post-navigation-link__arrow-previous"
            ],
            "relatedUrlId": "3020c3f0-c850-443d-beb2-8768175dfc1f",
            "equalified": false
        },
        {
            "nodeId": "46843bc9-95be-49de-947f-753f0e792588",
            "html": "<div class=\"gform-body gform_body\">",
            "targets": [
                ".gform-body"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "4cdf76fe-72d3-4a0d-99b5-b599a6c2a731",
            "html": "<div id=\"player\" style=\"width: 100%; height: 100%;\">",
            "targets": [
                "iframe[width=\"500\"]",
                "#player"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "4d29865a-112b-4739-ac53-25ebe5922cef",
            "html": "<select name=\"input_3\" id=\"input_2_3\" class=\"large gfield_select\" aria-required=\"true\" aria-invalid=\"false\"><option value=\"No thanks!\">No thanks!</option><option value=\"Yes, please email me about a demo.\">Yes, please email me about a demo.</option></select>",
            "targets": [
                "#input_2_3"
            ],
            "relatedUrlId": "4cb5098d-34a9-46fb-b4d5-6ce071418ca0",
            "equalified": false
        },
        {
            "nodeId": "4e27acec-7b19-478c-b9df-c27a60320d47",
            "html": "<strong>Equalify is a web accessibility platform made for Pros</strong>",
            "targets": [
                ".wp-container-core-group-is-layout-5 > p:nth-child(2) > strong"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "50673788-db96-4965-b9db-c2db725dff57",
            "html": "<span class=\"wp-block-social-link-label screen-reader-text\">Equalify LinkedIn</span>",
            "targets": [
                ".wp-social-link-linkedin > .wp-block-social-link-anchor > .wp-block-social-link-label.screen-reader-text"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "5364257b-8b24-44f5-8923-c4da9e7a40a8",
            "html": "<span class=\"wp-block-social-link-label screen-reader-text\">Equalify YouTube Channel</span>",
            "targets": [
                ".wp-social-link-youtube > .wp-block-social-link-anchor > .wp-block-social-link-label.screen-reader-text"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "55a1ac9a-c20a-4d03-9009-15e0b79f485c",
            "html": "<figcaption class=\"wp-element-caption\">Equalify Version 1 Video Walkthrough</figcaption>",
            "targets": [
                "figcaption"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "57c45121-9739-49e8-8252-92f88d201e94",
            "html": "<span class=\"wp-block-post-navigation-link__arrow-previous is-arrow-arrow\" aria-hidden=\"true\">←</span>",
            "targets": [
                ".wp-block-post-navigation-link__arrow-previous"
            ],
            "relatedUrlId": "1bf5496c-2f48-4d1d-91ee-42b99eae9f00",
            "equalified": false
        },
        {
            "nodeId": "5a8cee64-ffbc-4db8-90d2-34ec27e11444",
            "html": "<figcaption class=\"wp-element-caption\">Equalify Version 1 Video Walkthrough</figcaption>",
            "targets": [
                "figcaption"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "5b4eaa5d-0d6e-4db5-8120-219c2775b4da",
            "html": "<div class=\"wp-block-cover__inner-container is-layout-flow wp-block-cover-is-layout-flow\">",
            "targets": [
                ".wp-block-cover__inner-container"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "5ceedbe2-4754-4983-8f01-2d23cc940370",
            "html": "<div class=\"wp-block-group has-global-padding is-layout-constrained wp-block-group-is-layout-constrained\">",
            "targets": [
                ".wp-container-core-group-is-layout-7 > .has-global-padding.is-layout-constrained.wp-block-group-is-layout-constrained"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "5ea89c1f-279d-41c1-8dac-ef58efeb5ce4",
            "html": "<span class=\"wp-block-social-link-label screen-reader-text\">Equalify YouTube Channel</span>",
            "targets": [
                ".wp-social-link-youtube > .wp-block-social-link-anchor > .wp-block-social-link-label.screen-reader-text"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "6375841e-8ef9-415b-895a-bbc818e3312a",
            "html": "<a class=\"wp-block-button__link has-contrast-2-color has-text-color has-link-color has-text-align-left wp-element-button\" href=\"https://calendly.com/equalifyapp/15-minute-demo\" style=\"border-width:2px;padding-top:var(--wp--preset--spacing--10);padding-right:var(--wp--preset--spacing--20);padding-bottom:var(--wp--preset--spacing--10);padding-left:var(--wp--preset--spacing--20)\">",
            "targets": [
                ".wp-container-core-buttons-is-layout-2 > .is-style-outline.is-style-outline--064448592694e5040dbfe16027fad2b4.wp-block-button > .has-contrast-2-color.wp-block-button__link.wp-element-button"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "6850c56c-1760-4d29-90e0-e93a7ba18ed1",
            "html": "<p class=\"has-text-align-left\" style=\"font-size:clamp(2.089rem, 2.089rem + ((1vw - 0.2rem) * 2.768), 3.75rem);font-style:normal;font-weight:700;line-height:1.2\">Efficient. Open. Accessible.</p>",
            "targets": [
                ".wp-container-core-group-is-layout-5 > .has-text-align-left:nth-child(1)"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "6a1bd43a-6cba-4cb1-ae38-6b98d4670771",
            "html": "<h3 id=\"reply-title\" class=\"comment-reply-title\">Leave a Reply <small><a rel=\"nofollow\" id=\"cancel-comment-reply-link\" href=\"/version-one-preview/#respond\" style=\"display:none;\">Cancel reply</a></small></h3>",
            "targets": [
                "#reply-title"
            ],
            "relatedUrlId": "4cb5098d-34a9-46fb-b4d5-6ce071418ca0",
            "equalified": false
        },
        {
            "nodeId": "6ad187e3-5962-4daf-a7ec-84b56f426c59",
            "html": "<video tabindex=\"-1\" class=\"video-stream html5-main-video\" webkit-playsinline=\"\" playsinline=\"\" controlslist=\"nodownload\" style=\"width: 672px; height: 378px; left: 0px; top: -378px;\"></video>",
            "targets": [
                "iframe",
                "video"
            ],
            "relatedUrlId": "3020c3f0-c850-443d-beb2-8768175dfc1f",
            "equalified": false
        },
        {
            "nodeId": "6db5de07-277b-482f-8dc1-6c83f8f7c91e",
            "html": "<h2 class=\"wp-block-heading has-text-align-center is-style-default has-base-color has-text-color has-link-color wp-elements-2c5a5cd64a293274d72406b7a81ba5a7\" style=\"margin-top:0;margin-bottom:0\">Recent Updates</h2>",
            "targets": [
                ".wp-elements-2c5a5cd64a293274d72406b7a81ba5a7"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "6dff071a-aa8d-438e-82bd-e18c19b62102",
            "html": "<p style=\"font-size:clamp(1.146rem, 1.146rem + ((1vw - 0.2rem) * 1.09), 1.8rem);\"><strong>Equalify is a web accessibility platform made for Pros</strong>. Our latest version launches Equalify’s core web accessibility tools.</p>",
            "targets": [
                ".wp-container-core-group-is-layout-5 > p:nth-child(2)"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "743793ad-380c-40a9-a6b3-a0cf4e1cec91",
            "html": "<span class=\"wp-block-post-navigation-link__arrow-previous is-arrow-arrow\" aria-hidden=\"true\">←</span>",
            "targets": [
                ".wp-block-post-navigation-link__arrow-previous"
            ],
            "relatedUrlId": "bd0438e1-530a-4cf9-8e6d-d464b590e161",
            "equalified": false
        },
        {
            "nodeId": "792fa88d-1856-4438-bb8c-6dd9414d642d",
            "html": "<select name=\"input_3\" id=\"input_2_3\" class=\"large gfield_select\" aria-required=\"true\" aria-invalid=\"false\"><option value=\"No thanks!\">No thanks!</option><option value=\"Yes, please email me about a demo.\">Yes, please email me about a demo.</option></select>",
            "targets": [
                "#input_2_3"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "813d998f-bf95-484d-a6ec-cd9edee2ba91",
            "html": "<h2 class=\"wp-block-heading\">Get the Latest!</h2>",
            "targets": [
                ".are-vertically-aligned-center > .wp-block-column.is-vertically-aligned-center.wp-block-column-is-layout-flow:nth-child(1) > .has-global-padding.is-layout-constrained.wp-block-group-is-layout-constrained > h2"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "83f60cdf-44cc-4f68-b706-cd76860c2f9e",
            "html": "<video tabindex=\"-1\" class=\"video-stream html5-main-video\" webkit-playsinline=\"\" playsinline=\"\" controlslist=\"nodownload\" style=\"width: 500px; height: 281px; left: 0px; top: -281px;\"></video>",
            "targets": [
                "iframe",
                "video"
            ],
            "relatedUrlId": "c2ebd5fb-7158-4b01-8541-0389b5877508",
            "equalified": false
        },
        {
            "nodeId": "894bce7e-7b85-4fd6-9f21-40d393451054",
            "html": "<span class=\"wp-block-social-link-label screen-reader-text\">Equalify on X (Formally Twitter)</span>",
            "targets": [
                ".wp-social-link-x > a[href$=\"equalifyapp\"] > .wp-block-social-link-label.screen-reader-text"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "8d65b6d8-4260-4deb-8712-67c572cf83f3",
            "html": "<div class=\"wp-block-group alignfull has-base-2-background-color has-background is-layout-flow wp-block-group-is-layout-flow\" style=\"border-top-style:none;border-top-width:0px;border-right-style:none;border-right-width:0px;border-bottom-color:var(--wp--preset--color--contrast-3);border-bottom-width:1px;border-left-style:none;border-left-width:0px;margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--10);padding-right:var(--wp--preset--spacing--10);padding-bottom:var(--wp--preset--spacing--10);padding-left:var(--wp--preset--spacing--10)\">",
            "targets": [
                ".wp-block-group-is-layout-flow.has-base-2-background-color.alignfull"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "90d460cc-8e4a-4e32-9618-1ebfa47a4b06",
            "html": "<a href=\"https://equalify.app/category/editorial/\" rel=\"tag\">Editorial</a>",
            "targets": [
                ".taxonomy-category > a[rel=\"tag\"]"
            ],
            "relatedUrlId": "1bf5496c-2f48-4d1d-91ee-42b99eae9f00",
            "equalified": false
        },
        {
            "nodeId": "9414cb32-04de-42da-a0be-900d0b21d984",
            "html": "<div class=\"wp-block-cover__inner-container is-layout-flow wp-block-cover-is-layout-flow\">",
            "targets": [
                ".wp-block-cover__inner-container"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "966624bf-fe7d-4205-bf07-03410f7770a7",
            "html": "<textarea id=\"comment\" name=\"comment\" cols=\"45\" rows=\"8\" maxlength=\"65525\" required=\"\"></textarea>",
            "targets": [
                "#comment"
            ],
            "relatedUrlId": "bd0438e1-530a-4cf9-8e6d-d464b590e161",
            "equalified": false
        },
        {
            "nodeId": "97257912-598e-4c60-a421-a5bd2757379f",
            "html": "<h3 class=\"wp-block-heading is-style-default\" style=\"margin-top:var(--wp--preset--spacing--20)\">Join Our Newsletter</h3>",
            "targets": [
                ".wp-block-column.is-vertically-aligned-center.wp-block-column-is-layout-flow:nth-child(1) > .has-global-padding.is-layout-constrained.wp-block-group-is-layout-constrained > .is-style-default"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "9b48d71d-8c9d-4b26-af52-9c317ef5e014",
            "html": "<p>Enter your email to get updates from Equalify:</p>",
            "targets": [
                ".are-vertically-aligned-center > .wp-block-column.is-vertically-aligned-center.wp-block-column-is-layout-flow:nth-child(1) > .has-global-padding.is-layout-constrained.wp-block-group-is-layout-constrained > p"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "9c7f6405-5605-4572-ab3b-36e4584ed213",
            "html": "<a href=\"https://equalify.app/category/news/\" rel=\"tag\">News</a>",
            "targets": [
                ".taxonomy-category > a[rel=\"tag\"]"
            ],
            "relatedUrlId": "4cb5098d-34a9-46fb-b4d5-6ce071418ca0",
            "equalified": false
        },
        {
            "nodeId": "a4b0923e-e52d-4f44-843c-c6bf88aa70f5",
            "html": "<p>Enter your email to get updates from Equalify:</p>",
            "targets": [
                ".are-vertically-aligned-center > .wp-block-column.is-vertically-aligned-center.wp-block-column-is-layout-flow:nth-child(1) > .has-global-padding.is-layout-constrained.wp-block-group-is-layout-constrained > p"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "a4fe7f97-c455-4660-b897-a67cd73be96f",
            "html": "<div class=\"wp-block-group alignfull has-global-padding is-layout-constrained wp-container-core-group-is-layout-19 wp-block-group-is-layout-constrained\" style=\"border-top-color:var(--wp--preset--color--accent-5);border-top-width:1px;margin-top:0;padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--10);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--10)\">",
            "targets": [
                ".wp-container-core-group-is-layout-19"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "a5f3efbe-90de-41ea-8f5f-e7b3c1d7cf45",
            "html": "<strong>Equalify is a web accessibility platform made for Pros</strong>",
            "targets": [
                ".wp-container-core-group-is-layout-5 > p:nth-child(2) > strong"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "a959dae6-c13c-4002-aad7-2b9e672fedae",
            "html": "<div class=\"wp-block-group alignfull has-global-padding is-layout-constrained wp-container-core-group-is-layout-5 wp-block-group-is-layout-constrained has-background\" style=\"border-bottom-color:var(--wp--preset--color--contrast-3);border-bottom-width:1px;margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--50);padding-right:var(--wp--preset--spacing--10);padding-bottom:var(--wp--preset--spacing--50);padding-left:var(--wp--preset--spacing--10);background-image:url('https://equalify.app/wp-content/uploads/2024/07/Equalify-banners-and-icons.001-1.jpeg');background-position:47% 100%;background-size:cover;\">",
            "targets": [
                ".wp-container-core-group-is-layout-5"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "ab8dfc38-48db-4bc5-8521-bbea5b455f96",
            "html": "<div id=\"player\" style=\"width: 100%; height: 100%;\">",
            "targets": [
                "iframe[width=\"500\"]",
                "#player"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "b2ba7688-5022-4033-8a6a-ff1d522bbafc",
            "html": "<textarea id=\"comment\" name=\"comment\" cols=\"45\" rows=\"8\" maxlength=\"65525\" required=\"\"></textarea>",
            "targets": [
                "#comment"
            ],
            "relatedUrlId": "4cb5098d-34a9-46fb-b4d5-6ce071418ca0",
            "equalified": false
        },
        {
            "nodeId": "b6c9bd3e-5ae3-4918-a69d-fe247aa50e03",
            "html": "<span class=\"wp-block-social-link-label screen-reader-text\">Equalify GitHub Organization</span>",
            "targets": [
                ".wp-social-link-github > .wp-block-social-link-anchor > .wp-block-social-link-label.screen-reader-text"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "bc790f19-9602-4d48-bfdc-a050e2627bab",
            "html": "<div class=\"html5-video-player ytp-exp-bottom-control-flexbox ytp-modern-caption ytp-title-enable-channel-logo ytp-fine-scrubbing-exp ytp-embed ytp-embed-playlist unstarted-mode ytp-hide-controls ytp-small-mode\" tabindex=\"-1\" id=\"movie_player\" data-version=\"/s/player/d2e656ee/player_ias.vflset/en_US/base.js\" aria-label=\"YouTube Video Player\">",
            "targets": [
                "iframe[width=\"500\"]",
                "#movie_player"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "c0f695d0-be91-4f97-880b-97b52bdd1fd4",
            "html": "<p class=\"has-text-align-left has-small-font-size\">After the demo, you’ll receive Free Trial access.</p>",
            "targets": [
                ".has-small-font-size.has-text-align-left"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "c4c9730b-cdf4-4bfa-8426-8eaad7d175d3",
            "html": "<h3 class=\"wp-block-heading has-text-align-center is-style-default\" style=\"margin-top:0\">Social Links</h3>",
            "targets": [
                ".wp-container-core-group-is-layout-29 > .is-style-default"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "cde0e634-b68d-417b-9f0f-8cdc19b16ea6",
            "html": "<p style=\"font-size:clamp(1.146rem, 1.146rem + ((1vw - 0.2rem) * 1.09), 1.8rem);\"><strong>Equalify is a web accessibility platform made for Pros</strong>. Our latest version launches Equalify’s core web accessibility tools.</p>",
            "targets": [
                ".wp-container-core-group-is-layout-5 > p:nth-child(2)"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "ce79ff98-3fcd-4b7e-9c93-081f715bf555",
            "html": "<select name=\"input_3\" id=\"input_2_3\" class=\"large gfield_select\" aria-required=\"true\" aria-invalid=\"false\"><option value=\"No thanks!\">No thanks!</option><option value=\"Yes, please email me about a demo.\">Yes, please email me about a demo.</option></select>",
            "targets": [
                "#input_2_3"
            ],
            "relatedUrlId": "bd0438e1-530a-4cf9-8e6d-d464b590e161",
            "equalified": false
        },
        {
            "nodeId": "cf018d0c-e51e-471c-8789-8b6c27478ed1",
            "html": "<div class=\"html5-video-player ytp-exp-bottom-control-flexbox ytp-modern-caption ytp-title-enable-channel-logo ytp-fine-scrubbing-exp ytp-embed ytp-embed-playlist unstarted-mode ytp-hide-controls ytp-large-width-mode\" tabindex=\"-1\" id=\"movie_player\" data-version=\"/s/player/250a2ff7/player_ias.vflset/en_US/base.js\" aria-label=\"YouTube Video Player\">",
            "targets": [
                "iframe",
                "#movie_player"
            ],
            "relatedUrlId": "3020c3f0-c850-443d-beb2-8768175dfc1f",
            "equalified": false
        },
        {
            "nodeId": "d31c00c2-636a-4b04-9d13-e15e0ffea1ee",
            "html": "<div class=\"wp-block-group alignfull has-global-padding is-layout-constrained wp-container-core-group-is-layout-5 wp-block-group-is-layout-constrained has-background\" style=\"border-bottom-color:var(--wp--preset--color--contrast-3);border-bottom-width:1px;margin-top:0;margin-bottom:0;padding-top:var(--wp--preset--spacing--50);padding-right:var(--wp--preset--spacing--10);padding-bottom:var(--wp--preset--spacing--50);padding-left:var(--wp--preset--spacing--10);background-image:url('https://equalify.app/wp-content/uploads/2024/07/Equalify-banners-and-icons.001-1.jpeg');background-position:47% 100%;background-size:cover;\">",
            "targets": [
                ".wp-container-core-group-is-layout-5"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "d98b5461-d78f-4d42-88d5-06a1fb3bd1b5",
            "html": "<div class=\"html5-video-player ytp-exp-bottom-control-flexbox ytp-modern-caption ytp-title-enable-channel-logo ytp-fine-scrubbing-exp ytp-embed ytp-embed-playlist unstarted-mode ytp-hide-controls ytp-small-mode\" tabindex=\"-1\" id=\"movie_player\" data-version=\"/s/player/250a2ff7/player_ias.vflset/en_US/base.js\" aria-label=\"YouTube Video Player\">",
            "targets": [
                "iframe[width=\"500\"]",
                "#movie_player"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "dbcc35cb-8520-45a4-bb18-9f2cbd02efdf",
            "html": "<span class=\"wp-block-social-link-label screen-reader-text\">Equalify on X (Formally Twitter)</span>",
            "targets": [
                ".wp-social-link-x > a[href$=\"equalifyapp\"] > .wp-block-social-link-label.screen-reader-text"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "ddeac529-ba51-4e46-8e26-3a9664d06edd",
            "html": "<video tabindex=\"-1\" class=\"video-stream html5-main-video\" webkit-playsinline=\"\" playsinline=\"\" controlslist=\"nodownload\" style=\"width: 500px; height: 281px; left: 0px; top: -281px;\"></video>",
            "targets": [
                "iframe[width=\"500\"]",
                "video"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "e53ad313-f6ac-4058-b3e6-5d861570a9a5",
            "html": "<h3 class=\"wp-block-heading is-style-default\" style=\"margin-top:var(--wp--preset--spacing--20)\">Join Our Newsletter</h3>",
            "targets": [
                ".wp-block-column.is-vertically-aligned-center.wp-block-column-is-layout-flow:nth-child(1) > .has-global-padding.is-layout-constrained.wp-block-group-is-layout-constrained > .is-style-default"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "f45110e7-d444-4094-85ad-ad3c3c7ee9ad",
            "html": "<span class=\"wp-block-post-navigation-link__arrow-next is-arrow-arrow\" aria-hidden=\"true\">→</span>",
            "targets": [
                ".wp-block-post-navigation-link__arrow-next"
            ],
            "relatedUrlId": "4cb5098d-34a9-46fb-b4d5-6ce071418ca0",
            "equalified": false
        },
        {
            "nodeId": "f547c3be-73df-4fc2-a9d9-3a0e4556afe7",
            "html": "<p class=\"has-text-align-center has-small-font-size\"><em>Together we can Equalify the internet.</em></p>",
            "targets": [
                ".wp-container-core-group-is-layout-29 > .has-small-font-size.has-text-align-center"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "f7904580-5bf3-47c7-9ed4-0a1da529ad8b",
            "html": "<p class=\"has-text-align-left has-small-font-size\">After the demo, you’ll receive Free Trial access.</p>",
            "targets": [
                ".has-small-font-size.has-text-align-left"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        },
        {
            "nodeId": "fe8c5e7a-c0aa-40a4-8494-80d738434d7f",
            "html": "<p class=\"has-text-align-left\" style=\"font-size:clamp(2.089rem, 2.089rem + ((1vw - 0.2rem) * 2.768), 3.75rem);font-style:normal;font-weight:700;line-height:1.2\">Efficient. Open. Accessible.</p>",
            "targets": [
                ".wp-container-core-group-is-layout-5 > .has-text-align-left:nth-child(1)"
            ],
            "relatedUrlId": "d13ca549-1c4a-44ec-b87e-740ced18b3a1",
            "equalified": false
        }
    ],
    "messages": [
        {
            "id": "17173ec9-aace-4853-92d8-72cee80f0db3",
            "message": "Some page content is not contained by landmarks",
            "type": "violation",
            "equalifiedCount": 0,
            "activeCount": 34,
            "totalCount": 34
        },
        {
            "id": "fee14569-6fda-4f0c-9741-74de713d117a",
            "message": "Region Rule: Ensures all page content is contained by landmarks. All page content should be contained by landmarks. More information: https://dequeuniversity.com/rules/axe/4.9/region?application=axe-puppeteer",
            "type": "violation",
            "equalifiedCount": 0,
            "activeCount": 34,
            "totalCount": 34
        },
        {
            "id": "26fd9626-28d5-4e8d-a110-0ca05ae47547",
            "message": "Color Contrast Rule: Ensures the contrast between foreground and background colors meets WCAG 2 AA minimum contrast ratio thresholds. Elements must meet minimum color contrast ratio thresholds. More information: https://dequeuniversity.com/rules/axe/4.9/color-contrast?application=axe-puppeteer",
            "type": "error",
            "equalifiedCount": 0,
            "activeCount": 27,
            "totalCount": 27
        },
        {
            "id": "ea228c15-adc7-4ef7-944c-6e9a5ba693fc",
            "message": "Element's background color could not be determined due to a background image",
            "type": "error",
            "equalifiedCount": 0,
            "activeCount": 16,
            "totalCount": 16
        },
        {
            "id": "886689e4-1014-4913-9c34-9d5b69bec78e",
            "message": "Element content contains only non-text characters",
            "type": "error",
            "equalifiedCount": 0,
            "activeCount": 6,
            "totalCount": 6
        },
        {
            "id": "80329f6c-ad8d-4ac6-b27f-a5e6cac0dcef",
            "message": "Aria Prohibited Attr Rule: Ensures ARIA attributes are not prohibited for an element's role. Elements must only use permitted ARIA attributes. More information: https://dequeuniversity.com/rules/axe/4.9/aria-prohibited-attr?application=axe-puppeteer",
            "type": "error",
            "equalifiedCount": 0,
            "activeCount": 4,
            "totalCount": 4
        },
        {
            "id": "eee41d7f-6657-4389-a803-92b45da3527f",
            "message": "Video Caption Rule: Ensures <video> elements have captions. <video> elements must have captions. More information: https://dequeuniversity.com/rules/axe/4.9/video-caption?application=axe-puppeteer",
            "type": "error",
            "equalifiedCount": 0,
            "activeCount": 4,
            "totalCount": 4
        },
        {
            "id": "665482ea-2270-4975-bbf5-00212ffea29d",
            "message": "Element's contrast ratio could not be determined because of element overlap",
            "type": "error",
            "equalifiedCount": 0,
            "activeCount": 3,
            "totalCount": 3
        },
        {
            "id": "28867c64-9458-4ebd-85ae-3118dca72ca9",
            "message": "Link In Text Block Rule: Ensure links are distinguished from surrounding text in a way that does not rely on color. Links must be distinguishable without relying on color. More information: https://dequeuniversity.com/rules/axe/4.9/link-in-text-block?application=axe-puppeteer",
            "type": "error",
            "equalifiedCount": 0,
            "activeCount": 3,
            "totalCount": 3
        },
        {
            "id": "cfb1ef22-8092-4c1b-8a91-af38b7d51b6f",
            "message": "Element's background color could not be determined because it's partially obscured by another element",
            "type": "error",
            "equalifiedCount": 0,
            "activeCount": 3,
            "totalCount": 3
        },
        {
            "id": "b8e1836e-13f0-417f-9336-443864ddf72e",
            "message": "Element's background color could not be determined because element contains an image node",
            "type": "error",
            "equalifiedCount": 0,
            "activeCount": 2,
            "totalCount": 2
        },
        {
            "id": "65c43043-f831-4b6c-9f1f-3ddab5270e62",
            "message": "Heading Order Rule: Ensures the order of headings is semantically correct. Heading levels should only increase by one. More information: https://dequeuniversity.com/rules/axe/4.9/heading-order?application=axe-puppeteer",
            "type": "violation",
            "equalifiedCount": 0,
            "activeCount": 1,
            "totalCount": 1
        },
        {
            "id": "ed6db8b6-705c-4b85-ad6e-de1d0327bec7",
            "message": "Heading order invalid",
            "type": "violation",
            "equalifiedCount": 0,
            "activeCount": 1,
            "totalCount": 1
        }
    ],
    "tags": [
        {
            "id": "6f8f25e9-283e-4a99-87bc-f7bb6fb6901e",
            "tag": "wcag412"
        },
        {
            "id": "7b2e955e-2866-4adf-9d3e-f78c690fcac2",
            "tag": "EN-301-549"
        },
        {
            "id": "24a31237-2ccc-4a80-8c1a-73a162bc5fbd",
            "tag": "axe-core Rule"
        },
        {
            "id": "0114725c-eda3-48ba-bf9d-9fb2a2adf1f0",
            "tag": "wcag2a"
        },
        {
            "id": "f97aaa56-2743-4bc9-9ca2-cf6edac69d6a",
            "tag": "cat.aria"
        },
        {
            "id": "970a9a5a-dc8b-4021-b83e-6c10935e04ce",
            "tag": "EN-9.4.1.2"
        },
        {
            "id": "e30d0667-3865-42b5-8c60-2c882147e6b7",
            "tag": "EN-9.1.4.3"
        },
        {
            "id": "a5505c25-b838-4dec-80bb-0a98757f0a80",
            "tag": "TT13.c"
        },
        {
            "id": "e95151d1-d988-4747-b64b-9d333210c7b5",
            "tag": "ACT"
        },
        {
            "id": "0bd81740-c692-48d8-825b-d91e1518cd85",
            "tag": "cat.color"
        },
        {
            "id": "615c4fee-5493-458a-a0ed-fc08f598b01e",
            "tag": "wcag2aa"
        },
        {
            "id": "6c5ae686-2296-4806-adb7-a64bfcc1d869",
            "tag": "wcag143"
        },
        {
            "id": "cadc60cf-fa0c-4097-a054-14299e0d5862",
            "tag": "TTv5"
        },
        {
            "id": "11c3102b-cd05-409a-8d7d-e55e371aeb60",
            "tag": "axe-core Message"
        },
        {
            "id": "841a436b-16de-496f-a143-c731641ccf4b",
            "tag": "best-practice"
        },
        {
            "id": "d2b450fe-606b-4e38-bf1b-fd30a5e9e3bd",
            "tag": "cat.keyboard"
        },
        {
            "id": "4624d76f-c168-4448-9af8-4a1f98e3e376",
            "tag": "EN-9.1.4.1"
        },
        {
            "id": "d2a9e70d-c833-4d2a-9daa-98b28587a31c",
            "tag": "wcag141"
        },
        {
            "id": "41352e2f-082a-4b63-8bf2-500fd642a6da",
            "tag": "TT13.a"
        },
        {
            "id": "3e60c003-a7e2-4c3a-812a-ed34bea540bf",
            "tag": "cat.text-alternatives"
        },
        {
            "id": "9fccc29a-b4a9-4ac7-9390-7e89305eba0d",
            "tag": "section508"
        },
        {
            "id": "951bb780-0667-4bbb-b4a8-9a48241b34dd",
            "tag": "TT17.a"
        },
        {
            "id": "f7f4a277-3159-48a9-9943-407a1b47ee99",
            "tag": "section508.22.a"
        },
        {
            "id": "8af0d0f1-86f8-415a-ba5b-02e149ab754b",
            "tag": "wcag122"
        },
        {
            "id": "fed4e02f-f19b-4487-a36a-80b57626118f",
            "tag": "EN-9.1.2.2"
        },
        {
            "id": "b1b41aca-dfbe-421a-88d0-77723a847f1d",
            "tag": "cat.semantics"
        }
    ],
    "chart": [
        {
            "date": "2024-07-31",
            "equalified": 0,
            "active": 73
        }
    ]
}
```

I confirmed that report id `f6784696-f50d-4cec-bd85-e4aea7e4c441` has the filters:
```
{
            "id": "52330930-922d-484c-b24f-be6e501e309a",
            "name": "Equalify Website",
            "filters": [
                {
                    "type": "properties",
                    "label": "Equalify",
                    "value": "1f52de88-0b9a-4186-b406-040ed2a3e2cc"
                },
                {
                    "type": "messages",
                    "label": "Element does not have an alt attribute",
                    "value": "b033088f-d2cd-4515-a776-c86f29e503e7"
                }
            ],
            "activeIssues": 138,
            "mostCommonIssue": "Some page content is not contained by landmarks"
        }
```

**Comment by bbertucc** [comment]
@heythisischris where should I be testing this? on Staging? I don't see a note that it's up on staging and I am a robot-like human designed to follow our [deployment process](https://github.com/equalifyEverything/handbook?tab=readme-ov-file#deploying-updates)

**Comment by heythisischris** [comment]
Ah, I deployed it directly to production, but it should be deployed to staging as well.

**Comment by bbertucc** [comment]
Thanks @heythisischris - I wasn't able to test this on staging because of #424

But I did test on prod, and am still seeing more results than I expect. For instance, I added the issue `List item does not have a <ul>, <ol> parent element`.

The results included other messages (note the other messages are similar to that one I filtered against, so maybe the query operator isn't restricted enough):

```json
{
    "reportName": "Equalify Snippets",
    "urls": [
        {
            "id": "508cbb6e-5871-46b3-9a0f-1f865719b40e",
            "url": "https://equalify.app/why-form-labels-matter-for-web-accessibility-video/"
        }
    ],
    "nodes": [
        {
            "nodeId": "6e235113-5dc4-44b6-a0d5-2e2d9da84d16",
            "html": "<li>Equalify identifies unlabeled form elements, helping developers improve accessibility.</li>",
            "targets": [
                "li:nth-child(6)"
            ],
            "relatedUrlId": "508cbb6e-5871-46b3-9a0f-1f865719b40e",
            "equalified": false
        },
        {
            "nodeId": "860c33b6-0c06-4de7-98a2-4b1d476e71c1",
            "html": "<li>Labels are essential for users, especially those using screen readers.</li>",
            "targets": [
                "li:nth-child(5)"
            ],
            "relatedUrlId": "508cbb6e-5871-46b3-9a0f-1f865719b40e",
            "equalified": false
        },
        {
            "nodeId": "8ed01b2a-d94c-4cae-96c7-fd2bf6332cd5",
            "html": "<li>Labels provide context and meaning to form elements (text fields, checkboxes, radio buttons).</li>",
            "targets": [
                "li:nth-child(4)"
            ],
            "relatedUrlId": "508cbb6e-5871-46b3-9a0f-1f865719b40e",
            "equalified": false
        },
        {
            "nodeId": "067344c3-abcb-40f7-9347-08277fffa1a8",
            "html": "<li>Recommends using tools like Gravity Forms for WordPress that support accessibility out of the box.</li>",
            "targets": [
                "li:nth-child(7)"
            ],
            "relatedUrlId": "508cbb6e-5871-46b3-9a0f-1f865719b40e",
            "equalified": false
        },
        {
            "nodeId": "dbecc72c-afd2-477e-adf5-d285550f96dc",
            "html": "<li>New episodes published weekly.</li>",
            "targets": [
                "li:nth-child(10)"
            ],
            "relatedUrlId": "508cbb6e-5871-46b3-9a0f-1f865719b40e",
            "equalified": false
        },
        {
            "nodeId": "042adbe9-dd7d-4d06-ac69-3ad259a97df7",
            "html": "<li>Addresses common accessibility challenges and provides solutions for a more inclusive internet.</li>",
            "targets": [
                "li:nth-child(9)"
            ],
            "relatedUrlId": "508cbb6e-5871-46b3-9a0f-1f865719b40e",
            "equalified": false
        },
        {
            "nodeId": "8161f719-ebdc-44f1-9583-df686065ecb0",
            "html": "<li>Equalify Snippets offers practical tips and expert insights to improve web accessibility.</li>",
            "targets": [
                "li:nth-child(8)"
            ],
            "relatedUrlId": "508cbb6e-5871-46b3-9a0f-1f865719b40e",
            "equalified": false
        }
    ],
    "messages": [
        {
            "id": "eadc3230-6236-4b07-a227-b1ef601c7714",
            "message": "Listitem Rule: Ensures <li> elements are used semantically. <li> elements must be contained in a <ul> or <ol>. More information: https://dequeuniversity.com/rules/axe/4.9/listitem?application=axe-puppeteer",
            "type": "violation",
            "equalifiedCount": 0,
            "activeCount": 7,
            "totalCount": 7
        },
        {
            "id": "c77e0f6f-0771-45e8-a27a-8120550e4860",
            "message": "List item does not have a <ul>, <ol> parent element",
            "type": "violation",
            "equalifiedCount": 0,
            "activeCount": 7,
            "totalCount": 7
        }
    ],
    "tags": [
        {
            "id": "e1e9fb8d-094d-45ed-9ad9-9df621915bb4",
            "tag": "axe-core Rule"
        },
        {
            "id": "54429730-5264-49b7-86f8-5b88cefd00ef",
            "tag": "cat.structure"
        },
        {
            "id": "f3a67d91-b78d-41c8-a55c-40433114cd39",
            "tag": "wcag2a"
        },
        {
            "id": "87952bb2-1553-46ff-a3b9-45af2187ea6f",
            "tag": "wcag131"
        },
        {
            "id": "9a40065c-c8bf-49d9-899f-52566dc48dbe",
            "tag": "EN-301-549"
        },
        {
            "id": "32029cf7-d71d-45b2-a3db-e9adb726f686",
            "tag": "EN-9.1.3.1"
        },
        {
            "id": "beb87e2c-30ec-4af5-85b9-6b45fe68a4aa",
            "tag": "axe-core Message"
        }
    ],
    "chart": [
        {
            "date": "2024-08-07",
            "equalified": 0,
            "active": 7
        }
    ]
}
```
