### ISSUE TITLE
[Dashboard] On Edit Report screen, "Filter By:" dropdown can't be manually scrolled (Chrome only)

### ISSUE THREAD

**Issue by azdak** [bbertucc/equalify#426]
### To Reproduce
- Create or edit a report
- Trigger the combobox opening: 
![image](https://github.com/user-attachments/assets/a3b6ed61-77f2-4aaa-b9a9-09daa477f20d)
- Click on the scrollbar

This will cause the combobox to close prematurely (I'm guessing it's losing focus, triggering the combobox close). 

### Tested on
- Windows, Chrome
- Windows, Firefox (Issue does not appear)
- Wondows, Edge (Issue does not appear)

**Comment by azdak** [comment]
I _think_ the issue is here: https://github.com/EqualifyEverything/equalify-dashboard/blob/7d8c1e7fd1755cfa07d680ca7ac69e746750a479/src/components/inputs/typeahead.tsx#L161- I think using `click` instead of `mousedown` should fix it.

**Comment by bbertucc** [comment]
I'm not seeing this issue on Chrome or Safari in MacOS. Can you confirm it's still happening @azdak? We've done a few updates since you reported it.

**Comment by azdak** [comment]
Yup, can confirm still an issue on win10/Chrome

https://github.com/user-attachments/assets/98695ba6-e7c0-4f59-acbc-c8415925677f

**Comment by wilsuriel03** [comment]
@azdak I'm not seeing the issue on chrome. I tested both locally and in production.


https://github.com/user-attachments/assets/26491f20-71b0-4876-819c-d740f83cefb2

**Comment by bbertucc** [comment]
I'm going to ahead and say this is a weird problem with Trey's Chrome. But we can reopen it if an issue. An alternative will be to use a scroll.
